version: '3.8'
services:
  kamra-app:
    container_name: kamra-szerver
    build: .
    ports:
      - "3000:3000"
    volumes:     
      #- ./data:/app/data
      - ../kamra-app-data:/app/data
    restart: unless-stopped